### ISSUE TITLE
Create a LICENSE?

### ISSUE THREAD

**Issue by ghost** [Chootin/ChEdit#2]
- just for contributor's _ease-of-mind_ later.

**Comment by Chootin** [comment]
Done. Thanks for lending a hand!

Be aware I am still yet to separate the code out into properly documented files with sensible scopes and would like to redo how I am drawing the display. I hope we don't see bad merge conflicts in the near future :).

**Comment by ghost** [comment]
Hi, thanks for reviewing this issue. I also noticed that the texts next to the line number bar is too close with each other. One space identation in between might be a good idea, IMHO.

**Comment by Chootin** [comment]
Yeah I was thinking about that. 

I did make the majority of this code on a very small display (800x480) so I was thinking more about conservation of space at the time. I'll add it to the TODOs.

**Comment by ghost** [comment]
Good to know. Thanks.
